services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    env_file: .env
    volumes:
      - ./my_pgdata:/var/lib/postgresql/data
      - ./db/01_create_database.sql:/docker-entrypoint-initdb.d/01_create_database.sql
      - ./db/02_init_schema.sql:/docker-entrypoint-initdb.d/02_init_schema.sql
      - ./db/03_init_data.sql:/docker-entrypoint-initdb.d/03_init_data.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: my_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    name: postgres_data
